config:
  exporters:
    otlp/metrics:
      endpoint: api.honeycomb.io:443
      headers:
        "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
        "x-honeycomb-dataset": "demo-metrics"
  receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector-pods'
              scrape_interval: 5s
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - source_labels: [__meta_kubernetes_namespace]
                  action: replace
                  target_label: namespace
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: pod
                - action: replace
                  source_labels: 
                  - __meta_kubernetes_pod_annotation_honeycomb_io_metrics_path
                  target_label: __metrics_path__
                - action: replace
                  source_labels:
                  - __address__
                  - __meta_kubernetes_pod_annotation_honeycomb_io_scrape_port
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $$1:$$2
                  target_label: __address__
                - action: keep
                  source_labels: 
                  - __meta_kubernetes_pod_annotation_honeycomb_io_metrics
                  regex: true
  service:
    telemetry:
      logs:
        level: "debug"
    pipelines:
      metrics:
        receivers:
          - otlp
          - prometheus
        processors:
          - batch
        exporters:
          - otlp/metrics

podAnnotations:
  consul.hashicorp.com/connect-inject: 'false'
  consul.hashicorp.com/transparent-proxy: 'false'
