---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: default
automountServiceAccountToken: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: default
  labels:
    app: api_v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        metrics: enabled
      annotations:
        honeycomb.io/metrics: 'true'
        honeycomb.io/scrape_port: '9102'
        honeycomb.io/metrics_path: '/stats/prometheus'
        consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: '9102'
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: '9411'
    spec:  
      serviceAccountName: api
      automountServiceAccountToken: true
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.23.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: "NAME"
              value: "API V1"
            - name: "LISTEN_ADDR"
              value: "0.0.0.0:9090"
            - name: "TIMING_50_PERCENTILE"
              value: "10ms"
            - name: "TRACING_ZIPKIN"
              value: "http://opentelemetry-collector.default.svc:9411"
            - name: "READY_CHECK_RESPONSE_DELAY"
              value: "10s"
            - name: "PORT"
              value: "9090"
          readinessProbe:
            httpGet:
              path: /ready
              port: 9090
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 5
            initialDelaySeconds: 5
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: api
spec:
  protocol: http

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api
spec:
  destination:
    name: api
  sources:
    - name: web
      action: allow