---
apiVersion: v1
kind: Service
metadata:
  name: ingress-local
  namespace: default
  labels:
    app: ingress-local
spec:
  ports:
  - name: gateway-0
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: consul
    component: ingress-gateway
    ingress-gateway-name: consul-ingress-gateway
    release: consul
  sessionAffinity: None

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  tls:
    enabled: false
  listeners:
    - port: 80
      protocol: http
      services:
        - name: web
          hosts: ['*']