---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: default
automountServiceAccountToken: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: default
  labels:
    app: web_v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        metrics: enabled
      annotations:
        honeycomb.io/metrics: 'true'
        honeycomb.io/scrape_port: '9102'
        honeycomb.io/metrics_path: '/stats/prometheus'
        consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: '9101,9090'
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: '9411'
    spec:  
      serviceAccountName: web
      automountServiceAccountToken: true
      containers:
        - name: web
          image: nicholasjackson/fake-service:v0.23.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: "NAME"
              value: "WEB V1"
            - name: "LISTEN_ADDR"
              value: "0.0.0.0:9090"
            - name: "TIMING_50_PERCENTILE"
              value: "50ms"
            - name: "TRACING_ZIPKIN"
              value: "http://opentelemetry-collector.default.svc:9411"
            - name: "READY_CHECK_RESPONSE_DELAY"
              value: "10s"
            - name: "PORT"
              value: "9090"
            - name: "UPSTREAM_URIS"
              value: "http://api.default.svc:9090"
          readinessProbe:
            httpGet:
              path: /ready
              port: 9090
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 5
            initialDelaySeconds: 5

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: web
spec:
  protocol: http

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: web
spec:
  destination:
    name: web
  sources:
    - name: ingress-gateway
      action: allow